### ISSUE TITLE
How to use BrowserRouter

### ISSUE THREAD

**Issue by zhhyang** [jdf2e/rocketact#69]
# ❔ Question

RT

**Comment by beanlee** [comment]
Just try, Rocketact doesn't limit the way of react router, we support browser router.

https://github.com/jdf2e/rocketact/blob/220ce84e4e796764b4b1237b2b209f283a1be567/packages/rocketact-scripts/src/commands/start.ts#L50-L56

Since we support multi-page applications, the following configuration may help you guys:

```diff
<BrowserRouter>
    <React.Suspense fallback={<div>Loading</div>}>
      <Switch>
        <Route path="/routerA/" component={PageA}></Route>
        <Route
          path="/routerB/"
          component={PageB}
        ></Route>
+        <Route path="*" component={Index}></Route>
      </Switch>
    </React.Suspense>
</BrowserRouter>
```

Ensure that the **Index** route is accessed first
